version: '3.9'

services:

  postgres:
    image: postgres:15

    container_name: ai-doc-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: ai-doc-redis

    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.1

    container_name: ai-doc-opensearch

    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m

    ports:
      - "9200:9200"

    volumes:
      - opensearch_data:/usr/share/opensearch/data

  backend:
    build: ./backend

    container_name: ai-doc-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis
      - opensearch

  celery:
    build: ./backend

    container_name: ai-doc-celery

    command: celery -A app.tasks.document_tasks worker --pool=solo --loglevel=info

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis
      - opensearch

volumes:
  postgres_data:
  opensearch_data:

